# Generated by Django 5.1.6 on 2025-03-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_administrator_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='acces_token',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
