# Generated by Django 5.1.6 on 2025-03-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_administrator_acces_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='acces_token',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='member',
            name='access_token',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='access_token',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
