# Generated by Django 5.1.6 on 2025-03-12 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_acces_token_administrator_access_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
