# Generated by Django 5.1.7 on 2025-03-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_phonenumber_administrator_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='username',
            field=models.CharField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
