# Generated by Django 5.1.7 on 2025-04-04 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_member_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='access_token',
        ),
    ]
